"""fix timestamp Foreignkey

Revision ID: 3ca5c55c3d6c
Revises: 44fae2265a33
Create Date: 2024-11-22 14:47:05.333314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '3ca5c55c3d6c'
down_revision: Union[str, None] = '44fae2265a33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('timestamps_ibfk_1', 'timestamps', type_='foreignkey')
    op.create_foreign_key(None, 'timestamps', 'timestamps', ['workflow_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timestamps', type_='foreignkey')
    op.create_foreign_key('timestamps_ibfk_1', 'timestamps', 'workflows', ['workflow_id'], ['id'])
    # ### end Alembic commands ###
