"""make Timestamp into model

Revision ID: 44fae2265a33
Revises: 8e32f2b7b608
Create Date: 2024-11-19 18:11:43.612980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '44fae2265a33'
down_revision: Union[str, None] = '8e32f2b7b608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'trigger_day')
    op.drop_column('workflows', 'trigger_time')
    op.drop_column('workflows', 'trigger_frequency')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('trigger_frequency', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('workflows', sa.Column('trigger_time', mysql.DATETIME(), nullable=True))
    op.add_column('workflows', sa.Column('trigger_day', mysql.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
