"""workflow model migration

Revision ID: 48e3dcb1c607
Revises: e6d58c1f902c
Create Date: 2024-11-10 16:09:06.702129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '48e3dcb1c607'
down_revision: Union[str, None] = 'e6d58c1f902c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflows', 'trigger_time',
               existing_type=mysql.TIME(),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflows', 'trigger_time',
               existing_type=sa.DateTime(),
               type_=mysql.TIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
