"""updated gmailflow column name

Revision ID: 8e32f2b7b608
Revises: de0cc7ac7f5d
Create Date: 2024-11-13 15:41:58.518775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8e32f2b7b608'
down_revision: Union[str, None] = 'de0cc7ac7f5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gmailflow', sa.Column('recipient_email', sa.String(length=255), nullable=True))
    op.drop_index('ix_gmailflow_email', table_name='gmailflow')
    op.create_index(op.f('ix_gmailflow_recipient_email'), 'gmailflow', ['recipient_email'], unique=False)
    op.drop_column('gmailflow', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gmailflow', sa.Column('email', mysql.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f('ix_gmailflow_recipient_email'), table_name='gmailflow')
    op.create_index('ix_gmailflow_email', 'gmailflow', ['email'], unique=False)
    op.drop_column('gmailflow', 'recipient_email')
    # ### end Alembic commands ###
