"""gmail model migrate

Revision ID: de0cc7ac7f5d
Revises: 48e3dcb1c607
Create Date: 2024-11-11 13:08:15.762740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'de0cc7ac7f5d'
down_revision: Union[str, None] = '48e3dcb1c607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workflow_imported_data_id', table_name='workflow_imported_data')
    op.drop_table('workflow_imported_data')
    op.add_column('gmailflow', sa.Column('workflow_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'gmailflow', 'workflows', ['workflow_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gmailflow', type_='foreignkey')
    op.drop_column('gmailflow', 'workflow_id')
    op.create_table('workflow_imported_data',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('data', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=False),
    sa.Column('workflow_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name='workflow_imported_data_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_workflow_imported_data_id', 'workflow_imported_data', ['id'], unique=False)
    # ### end Alembic commands ###
