"""updated timestamp cascade

Revision ID: e8f003d553f1
Revises: 3ca5c55c3d6c
Create Date: 2024-12-02 15:15:38.709480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'e8f003d553f1'
down_revision: Union[str, None] = '3ca5c55c3d6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('timestamps_ibfk_1', 'timestamps', type_='foreignkey')
    op.create_foreign_key(None, 'timestamps', 'workflows', ['workflow_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timestamps', type_='foreignkey')
    op.create_foreign_key('timestamps_ibfk_1', 'timestamps', 'timestamps', ['workflow_id'], ['id'])
    # ### end Alembic commands ###
