name: Run Pytest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov  # Add coverage library

      - name: Set environment variables
        run: |
          echo "EMAIL=test@example.com" >> $GITHUB_ENV
          echo "PASS=testpassword" >> $GITHUB_ENV
          echo "JWT_SECRET=mysecretkey" >> $GITHUB_ENV
          echo "DATABASE_URL=sqlite:///./database.db" >> $GITHUB_ENV

      - name: Print all environment variables  # Debugging step
        run: |
          env

      - name: Run backend tests with coverage
        run: |
          cd backend
          PYTHONPATH=. pytest --cov=. --cov-report=html --cov-report=term-missing

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
