name: Run Pytest

on:
  push:
    branches:
      - tests/backend
  pull_request:
    branches:
      - tests/backend

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      EMAIL: test@example.com
      PASS: testpassword
      JWT_SECRET: mysecretkey
      DATABASE_URL: sqlite:///./database.db

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backend tests
        run: |
          cd backend
          PYTHONPATH=. pytest tests
